### PR TITLE
First draft for Humble

### PR DESCRIPTION
**Pull request by tomlogan501**
Hello,
Here is a first draft for the hyperdog under Humble.
Shout out to @CarlosRGN for initial work on it for the Opendog_ROS project on my repositories.

### CODE REVIEW

**Comment by NDHANA94** [comment]
Great! Thanks for your contribution!!!

**Comment by tomlogan501** [comment]
Wait ! Wait ! It's merged on foxy, I couldn't create a request for a target branch 
Can you revert and create a target branch ?

**Comment by NDHANA94** [comment]
Yeah, I already have reverted it and merged to a new humble branch. 
Thanks!

**Comment by NDHANA94** [comment]
btw, open_dog project is using all of my code. I would appreciate if you mention / acknowledge my repo in tha. Thanks!!!

**Comment by tomlogan501** [comment]
Sure, I will update it, I'm currently working on it :)
The idea was to merge Opendog and your repository for our robot.

**Comment by NDHANA94** [comment]
Great job :)
If you have any questions, do not hesitate to write me.
 Good luck!

**Pull request merged**
